<?php

declare(strict_types=1);

namespace ChronopostShipping;

/**
 * Class which returns the class map definition
 */
class ClassMap
{
    /**
     * Returns the mapping between the WSDL Structs and generated Structs' classes
     * This array is sent to the \SoapClient when calling the WS
     * @return string[]
     */
    final public static function get(): array
    {
        return [
            'esdResultContraintesAgenceValue' => '\\ChronopostShipping\\StructType\\EsdResultContraintesAgenceValue',
            'esdContraintesAgence' => '\\ChronopostShipping\\StructType\\EsdContraintesAgence',
            'resultGetReservedSkybillValue' => '\\ChronopostShipping\\StructType\\ResultGetReservedSkybillValue',
            'resultReservationExpeditionValue' => '\\ChronopostShipping\\StructType\\ResultReservationExpeditionValue',
            'esdValue' => '\\ChronopostShipping\\StructType\\EsdValue',
            'headerValue' => '\\ChronopostShipping\\StructType\\HeaderValue',
            'shipperValue' => '\\ChronopostShipping\\StructType\\ShipperValue',
            'customerValue' => '\\ChronopostShipping\\StructType\\CustomerValue',
            'recipientValue' => '\\ChronopostShipping\\StructType\\RecipientValue',
            'refValue' => '\\ChronopostShipping\\StructType\\RefValue',
            'skybillValue' => '\\ChronopostShipping\\StructType\\SkybillValue',
            'skybillParamsValue' => '\\ChronopostShipping\\StructType\\SkybillParamsValue',
            'scheduledValue' => '\\ChronopostShipping\\StructType\\ScheduledValue',
            'appointmentValue' => '\\ChronopostShipping\\StructType\\AppointmentValue',
            'resultExpeditionValue' => '\\ChronopostShipping\\StructType\\ResultExpeditionValue',
            'esdWithRefClientValue' => '\\ChronopostShipping\\StructType\\EsdWithRefClientValue',
            'esdWithRefClientValueV2' => '\\ChronopostShipping\\StructType\\EsdWithRefClientValueV2',
            'esdValue3' => '\\ChronopostShipping\\StructType\\EsdValue3',
            'headerValueV2' => '\\ChronopostShipping\\StructType\\HeaderValueV2',
            'shipperValueV2' => '\\ChronopostShipping\\StructType\\ShipperValueV2',
            'recipientValueV2' => '\\ChronopostShipping\\StructType\\RecipientValueV2',
            'refValueV2' => '\\ChronopostShipping\\StructType\\RefValueV2',
            'skybillWithDimensionsValue' => '\\ChronopostShipping\\StructType\\SkybillWithDimensionsValue',
            'skybillWithDimensionsValueV2' => '\\ChronopostShipping\\StructType\\SkybillWithDimensionsValueV2',
            'skybillWithDimensionsValueV3' => '\\ChronopostShipping\\StructType\\SkybillWithDimensionsValueV3',
            'skybillWithDimensionsValueV4' => '\\ChronopostShipping\\StructType\\SkybillWithDimensionsValueV4',
            'skybillWithDimensionsValueV5' => '\\ChronopostShipping\\StructType\\SkybillWithDimensionsValueV5',
            'skybillWithDimensionsValueV6' => '\\ChronopostShipping\\StructType\\SkybillWithDimensionsValueV6',
            'skybillWithDimensionsValueV7' => '\\ChronopostShipping\\StructType\\SkybillWithDimensionsValueV7',
            'skybillParamsValueV2' => '\\ChronopostShipping\\StructType\\SkybillParamsValueV2',
            'recipientLocalValue' => '\\ChronopostShipping\\StructType\\RecipientLocalValue',
            'recipientLocalValueV2' => '\\ChronopostShipping\\StructType\\RecipientLocalValueV2',
            'customsValue' => '\\ChronopostShipping\\StructType\\CustomsValue',
            'articleValue' => '\\ChronopostShipping\\StructType\\ArticleValue',
            'resultShippingValue' => '\\ChronopostShipping\\StructType\\ResultShippingValue',
            'resultMultiParcelExpeditionValue' => '\\ChronopostShipping\\StructType\\ResultMultiParcelExpeditionValue',
            'resultMultiParcelValue' => '\\ChronopostShipping\\StructType\\ResultMultiParcelValue',
            'resultExpeditionValueV3' => '\\ChronopostShipping\\StructType\\ResultExpeditionValueV3',
            'resultMonoParcelExpeditionValue' => '\\ChronopostShipping\\StructType\\ResultMonoParcelExpeditionValue',
            'resultGetRouting' => '\\ChronopostShipping\\StructType\\ResultGetRouting',
            'geopostResult' => '\\ChronopostShipping\\StructType\\GeopostResult',
            'skybillValueV2' => '\\ChronopostShipping\\StructType\\SkybillValueV2',
            'resultFaisabiliteESD' => '\\ChronopostShipping\\StructType\\ResultFaisabiliteESD',
            'donneurDOrdre' => '\\ChronopostShipping\\StructType\\DonneurDOrdre',
            'adresseEnlevement' => '\\ChronopostShipping\\StructType\\AdresseEnlevement',
            'adresseEnlevementV2' => '\\ChronopostShipping\\StructType\\AdresseEnlevementV2',
            'adresseEnlevementV3' => '\\ChronopostShipping\\StructType\\AdresseEnlevementV3',
            'particularitesEsd' => '\\ChronopostShipping\\StructType\\ParticularitesEsd',
            'options' => '\\ChronopostShipping\\StructType\\Options',
            'resultEnlevementNational' => '\\ChronopostShipping\\StructType\\ResultEnlevementNational',
            'infoEnlevement' => '\\ChronopostShipping\\StructType\\InfoEnlevement',
            'resultGetReservedSkybillWithTypeValue' => '\\ChronopostShipping\\StructType\\ResultGetReservedSkybillWithTypeValue',
            'destinatairesDpd' => '\\ChronopostShipping\\StructType\\DestinatairesDpd',
            'destinataireDpd' => '\\ChronopostShipping\\StructType\\DestinataireDpd',
            'adresseDestinataire' => '\\ChronopostShipping\\StructType\\AdresseDestinataire',
            'infoClient' => '\\ChronopostShipping\\StructType\\InfoClient',
            'particularites' => '\\ChronopostShipping\\StructType\\Particularites',
            'particularitesColisDpd' => '\\ChronopostShipping\\StructType\\ParticularitesColisDpd',
            'infoDouanieres' => '\\ChronopostShipping\\StructType\\InfoDouanieres',
            'resultPickupOrCollectionRequest' => '\\ChronopostShipping\\StructType\\ResultPickupOrCollectionRequest',
            'resultReservationMultiParcelExpeditionValue' => '\\ChronopostShipping\\StructType\\ResultReservationMultiParcelExpeditionValue',
            'resultParcelValue' => '\\ChronopostShipping\\StructType\\ResultParcelValue',
            'resultReservationMultiParcelExpeditionValueV2' => '\\ChronopostShipping\\StructType\\ResultReservationMultiParcelExpeditionValueV2',
            'resultAnnulerEnlevement' => '\\ChronopostShipping\\StructType\\ResultAnnulerEnlevement',
            'statut' => '\\ChronopostShipping\\StructType\\Statut',
            'entry' => '\\ChronopostShipping\\StructType\\Entry',
            'resultReservationExpeditionValueV2' => '\\ChronopostShipping\\StructType\\ResultReservationExpeditionValueV2',
            'skybillValueBase' => '\\ChronopostShipping\\StructType\\SkybillValueBase',
            'resultShippingInfo' => '\\ChronopostShipping\\StructType\\ResultShippingInfo',
            'error' => '\\ChronopostShipping\\StructType\\Error',
            'detail' => '\\ChronopostShipping\\StructType\\Detail',
            'shippingInfo' => '\\ChronopostShipping\\StructType\\ShippingInfo',
            'rechercherContraintesEnlevementV2' => '\\ChronopostShipping\\StructType\\RechercherContraintesEnlevementV2',
            'rechercherContraintesEnlevementV2Response' => '\\ChronopostShipping\\StructType\\RechercherContraintesEnlevementV2Response',
            'getReservedSkybill' => '\\ChronopostShipping\\StructType\\GetReservedSkybill',
            'getReservedSkybillResponse' => '\\ChronopostShipping\\StructType\\GetReservedSkybillResponse',
            'shippingWithReservationAndESDWithRefClientPC' => '\\ChronopostShipping\\StructType\\ShippingWithReservationAndESDWithRefClientPC',
            'shippingWithReservationAndESDWithRefClientPCResponse' => '\\ChronopostShipping\\StructType\\ShippingWithReservationAndESDWithRefClientPCResponse',
            'shippingV3' => '\\ChronopostShipping\\StructType\\ShippingV3',
            'shippingV3Response' => '\\ChronopostShipping\\StructType\\ShippingV3Response',
            'shippingV2' => '\\ChronopostShipping\\StructType\\ShippingV2',
            'shippingV2Response' => '\\ChronopostShipping\\StructType\\ShippingV2Response',
            'shippingWithESDOnlyV2' => '\\ChronopostShipping\\StructType\\ShippingWithESDOnlyV2',
            'shippingWithESDOnlyV2Response' => '\\ChronopostShipping\\StructType\\ShippingWithESDOnlyV2Response',
            'shippingMultiParcelV6' => '\\ChronopostShipping\\StructType\\ShippingMultiParcelV6',
            'shippingMultiParcelV6Response' => '\\ChronopostShipping\\StructType\\ShippingMultiParcelV6Response',
            'shippingMultiParcelV5' => '\\ChronopostShipping\\StructType\\ShippingMultiParcelV5',
            'shippingMultiParcelV5Response' => '\\ChronopostShipping\\StructType\\ShippingMultiParcelV5Response',
            'shippingV7' => '\\ChronopostShipping\\StructType\\ShippingV7',
            'shippingV7Response' => '\\ChronopostShipping\\StructType\\ShippingV7Response',
            'getRouting' => '\\ChronopostShipping\\StructType\\GetRouting',
            'getRoutingResponse' => '\\ChronopostShipping\\StructType\\GetRoutingResponse',
            'shippingMultiParcelV4' => '\\ChronopostShipping\\StructType\\ShippingMultiParcelV4',
            'shippingMultiParcelV4Response' => '\\ChronopostShipping\\StructType\\ShippingMultiParcelV4Response',
            'shippingV6' => '\\ChronopostShipping\\StructType\\ShippingV6',
            'shippingV6Response' => '\\ChronopostShipping\\StructType\\ShippingV6Response',
            'shippingMultiParcelV3' => '\\ChronopostShipping\\StructType\\ShippingMultiParcelV3',
            'shippingMultiParcelV3Response' => '\\ChronopostShipping\\StructType\\ShippingMultiParcelV3Response',
            'shippingV5' => '\\ChronopostShipping\\StructType\\ShippingV5',
            'shippingV5Response' => '\\ChronopostShipping\\StructType\\ShippingV5Response',
            'shippingMultiParcelV2' => '\\ChronopostShipping\\StructType\\ShippingMultiParcelV2',
            'shippingMultiParcelV2Response' => '\\ChronopostShipping\\StructType\\ShippingMultiParcelV2Response',
            'shippingV4' => '\\ChronopostShipping\\StructType\\ShippingV4',
            'shippingV4Response' => '\\ChronopostShipping\\StructType\\ShippingV4Response',
            'faisabiliteESD' => '\\ChronopostShipping\\StructType\\FaisabiliteESD',
            'faisabiliteESDResponse' => '\\ChronopostShipping\\StructType\\FaisabiliteESDResponse',
            'creerEnlevementNational' => '\\ChronopostShipping\\StructType\\CreerEnlevementNational',
            'creerEnlevementNationalResponse' => '\\ChronopostShipping\\StructType\\CreerEnlevementNationalResponse',
            'shippingWithESDOnly' => '\\ChronopostShipping\\StructType\\ShippingWithESDOnly',
            'shippingWithESDOnlyResponse' => '\\ChronopostShipping\\StructType\\ShippingWithESDOnlyResponse',
            'getReservedSkybillWithTypeAndModeByReservation' => '\\ChronopostShipping\\StructType\\GetReservedSkybillWithTypeAndModeByReservation',
            'getReservedSkybillWithTypeAndModeByReservationResponse' => '\\ChronopostShipping\\StructType\\GetReservedSkybillWithTypeAndModeByReservationResponse',
            'creerEnlevementEurope' => '\\ChronopostShipping\\StructType\\CreerEnlevementEurope',
            'creerEnlevementEuropeResponse' => '\\ChronopostShipping\\StructType\\CreerEnlevementEuropeResponse',
            'shippingMultiParcelWithReservation' => '\\ChronopostShipping\\StructType\\ShippingMultiParcelWithReservation',
            'shippingMultiParcelWithReservationResponse' => '\\ChronopostShipping\\StructType\\ShippingMultiParcelWithReservationResponse',
            'rechercherContraintesEnlevement' => '\\ChronopostShipping\\StructType\\RechercherContraintesEnlevement',
            'rechercherContraintesEnlevementResponse' => '\\ChronopostShipping\\StructType\\RechercherContraintesEnlevementResponse',
            'shippingWithReservationAndESDWithRefClient' => '\\ChronopostShipping\\StructType\\ShippingWithReservationAndESDWithRefClient',
            'shippingWithReservationAndESDWithRefClientResponse' => '\\ChronopostShipping\\StructType\\ShippingWithReservationAndESDWithRefClientResponse',
            'shippingMultiParcel' => '\\ChronopostShipping\\StructType\\ShippingMultiParcel',
            'shippingMultiParcelResponse' => '\\ChronopostShipping\\StructType\\ShippingMultiParcelResponse',
            'getSkybill' => '\\ChronopostShipping\\StructType\\GetSkybill',
            'getSkybillResponse' => '\\ChronopostShipping\\StructType\\GetSkybillResponse',
            'getReservedSkybillWithTypeAndModeAuth' => '\\ChronopostShipping\\StructType\\GetReservedSkybillWithTypeAndModeAuth',
            'getReservedSkybillWithTypeAndModeAuthResponse' => '\\ChronopostShipping\\StructType\\GetReservedSkybillWithTypeAndModeAuthResponse',
            'shipping' => '\\ChronopostShipping\\StructType\\Shipping',
            'shippingResponse' => '\\ChronopostShipping\\StructType\\ShippingResponse',
            'getReservedSkybillWithTypeAndMode' => '\\ChronopostShipping\\StructType\\GetReservedSkybillWithTypeAndMode',
            'getReservedSkybillWithTypeAndModeResponse' => '\\ChronopostShipping\\StructType\\GetReservedSkybillWithTypeAndModeResponse',
            'getReservedSkybillWithType' => '\\ChronopostShipping\\StructType\\GetReservedSkybillWithType',
            'getReservedSkybillWithTypeResponse' => '\\ChronopostShipping\\StructType\\GetReservedSkybillWithTypeResponse',
            'shippingMultiParcelWithReservationV3' => '\\ChronopostShipping\\StructType\\ShippingMultiParcelWithReservationV3',
            'shippingMultiParcelWithReservationV3Response' => '\\ChronopostShipping\\StructType\\ShippingMultiParcelWithReservationV3Response',
            'annulerEnlevements' => '\\ChronopostShipping\\StructType\\AnnulerEnlevements',
            'annulerEnlevementsResponse' => '\\ChronopostShipping\\StructType\\AnnulerEnlevementsResponse',
            'shippingMultiParcelWithReservationV2' => '\\ChronopostShipping\\StructType\\ShippingMultiParcelWithReservationV2',
            'shippingMultiParcelWithReservationV2Response' => '\\ChronopostShipping\\StructType\\ShippingMultiParcelWithReservationV2Response',
            'shippingWithReservationV2' => '\\ChronopostShipping\\StructType\\ShippingWithReservationV2',
            'shippingWithReservationV2Response' => '\\ChronopostShipping\\StructType\\ShippingWithReservationV2Response',
            'getShippingInformation' => '\\ChronopostShipping\\StructType\\GetShippingInformation',
            'getShippingInformationResponse' => '\\ChronopostShipping\\StructType\\GetShippingInformationResponse',
            'shippingWithReservation' => '\\ChronopostShipping\\StructType\\ShippingWithReservation',
            'shippingWithReservationResponse' => '\\ChronopostShipping\\StructType\\ShippingWithReservationResponse',
        ];
    }
}
